---
title: "Global Fishing"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10.2 / 2.54, fig.height = 5.3 / 2.54)
```

```{r}
library(tidyverse)
library(ggtext)
library(patchwork)
library(showtext)
library(ggdist)
library(scales)
library(MetBrewer)
```

```{r}
theme_set(
  theme_minimal(base_family = "Roboto Condensed", base_size = 12) +
    theme(
      plot.caption = element_markdown(size = 6, hjust = 0, lineheight = 1.2),
      plot.title = element_text(face = "bold", size = 15),
      plot.subtitle = element_textbox_simple(size = 12),
      panel.grid = element_blank(),
      axis.text = element_text(face = "bold"),
      legend.text = element_text(face = "bold"),
      legend.title = element_markdown(size = 10, halign = .5)
    )
)
```

```{r data}
languages <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-21/languages.csv")
```

```{r transform}
languages_filtered <- languages |>
  filter(type == "pl") |>
  arrange(language_rank) |>
  slice_head(n = 1000) |>
  select(id = pldb_id, rank = language_rank, appeared, title) |>
  arrange(rank) |>
  mutate(
    rank = row_number(),
    rank_bin = cut_width(rank + 1, width = 100, boundary = 1),
    rank_bin = fct_rev(rank_bin),
    appeared_bin = cut_width(appeared, width = 10, boundary = 0, closed = "left")
  ) |>
  mutate(
    fill = case_when(
      rank %in% 1:10 ~ "top25",
      appeared == 1948 ~ "first",
      id == "basic" ~ "first",
      id == "r" ~ "first",
      .default = "default"
    ),
    y = case_when(
      appeared == 1948 ~ .5,
      id == "basic" ~ 2,
      id == "c" ~ 1.5,
      id == "matlab" ~ 3.5,
      id == "cpp" ~ 3,
      id == "perl" ~ 3.5,
      id == "python" ~ 3,
      id == "r" ~ 3.6,
      id == "javascript" ~ 4.5,
      id == "java" ~ 4.2,
      id == "ruby" ~ 3.9,
      id == "php" ~ 3.6,
      id == "csharp" ~ 4.2,
      .default = 0
    )
  ) |> 
  arrange(fill)

languages_filtered |> 
  filter(fill == "top25")

languages_count_decade <- languages_filtered |>
  count(appeared_bin, .drop = FALSE) |>
  pull(n)

languages_count <- languages_filtered |>
  count(appeared_bin, rank_bin, .drop = FALSE)

main <- languages_count |>
  ggplot(aes(1930 + 10 * as.numeric(appeared_bin), rank_bin, fill = n)) +
  geom_point(aes(size = 45), shape = 21, fill = "grey90", stroke = 0, show.legend = FALSE) +
  geom_point(aes(size = n), shape = 21, stroke = 0) +
  scale_x_continuous(
    breaks = seq(1940, 2020, 10), labels = ~ paste0(.x, "s"),
    expand = expansion(add = c(5, 5)), position = "top",
    sec.axis = dup_axis(labels = paste0(c("n = ", rep("", 8)), languages_count_decade))
  ) +
  scale_y_discrete(labels = rev(c("Top 100", seq(200, 1000, 100)))) +
  scale_size_area(max_size = 12, breaks = seq(5, 45, 10), limits = c(0, 45)) +
  scale_fill_gradientn(
    colors = met.brewer("Johnson", direction = 1),
    breaks = seq(5, 45, 10), limits = c(0, 45)
  ) +
  labs(x = NULL, y = NULL, 
       size = "&#35; of Programming Laguages<br>per decade and rank bin", 
       fill = "&#35; of Programming Laguages<br>per decade and rank bin") +
  theme(legend.position = "bottom") +
  guides(
    fill = guide_legend(nrow = 1, label.position = "bottom"),
    size = guide_legend(nrow = 1, label.position = "bottom", title.vjust = .5, title.position = "right")
  )

top <- ggplot(languages_filtered, aes(y = 0, x = appeared, fill = fill)) +
  geom_hline(aes(yintercept = 0), linewidth = .25, color = "grey70") +
  geom_segment(
    data = ~ subset(., fill %in% c("first", "top25")),
    aes(xend = appeared, y = y), yend = 0, linewidth = .25,
    color = "grey70"
  ) +
  stat_dotsinterval(
    side = "top", scale = 0.7, slab_linewidth = NA,
    dotsize = 1.1, binwidth = .45, color = "transparent",
    n = 1000
  ) +
  geom_label(
    data = ~ subset(., fill %in% c("first", "top25")),
    aes(label = title, y = y), vjust = .5, size = 8 / .pt,
    family = "Roboto Condensed", fill = "white", label.size = 0
  ) +
  scale_x_continuous(limits = c(1940, NA), expand = expansion(add = c(5, 3)), labels = NULL) +
  scale_y_discrete(expand = c(0, .6, 0, .6)) +
  scale_fill_manual(
    values = c(
      default = "grey70",
      top25 = met.brewer("Austria", 3)[[1]],
      first = met.brewer("Austria", 3)[[3]]
    ),
    breaks = "top25", labels = "Top 10"
  ) +
  labs(x = NULL, y = NULL, fill = NULL) +
  coord_cartesian(clip = "off") +
  theme(
    axis.title = element_blank(),
    plot.margin = margin(t = 55, b = 5.5, l = 5.5, r = 5.5),
    legend.position = c(0, 0.1),
    legend.justification = c(0, 0.1)
  ) +
  guides(fill = guide_legend(override.aes = list(point_size = 10)))

top / main &
  plot_layout(heights = c(1, 2.5)) &
  plot_annotation(
    caption = "Original Data Source: pldb.com **\u2022** Illustration: Stefan Moog",
    title = "The Age of Programming Languages",
    subtitle = paste(
      "The age of programming languages started with **Plankalkül**.",
      "Developed in the 1940s by the German computer pioneer Konrad Zuse, Plankalkül was the first high programming language of the World.",
      "Since then, each decade has seen a record number of new programming languages.",
      "In the 2010s alone, 303 new programming languages have seen the light of day,",
      "more than in the first five decades (1940 to 1990) of the era of programming language combined.",
      "But only some made it to the top. The first to climb Olympus was **C**, which first appeared in 1972 and is listed as number 3 in the Programming Language Database (PLDB) ranking.",
      "The most productive year in this regard was 1995: 4 of the 15 programming languages which appeared in 1995 are ranked in the Top 10, including **Javascript**, **Java**, **PHP** and **Ruby**.",
      "Youngest member of this honorous club is **C#** which appeared in 2000."
    )
  )

ggsave("pldb.png", width = 1200, height = 1200, units = "px", dpi = 300, bg = "white", scale = 300 / 96)
```

```{r eval=FALSE}
range_rank <- range(languages_filtered$rank)
range_appeared <- range(languages_filtered$appeared)

languages_filtered |>
  select(id, rank, appeared) |>
  mutate(rank = rescale(rank, rev(range_appeared), range_rank)) |>
  pivot_longer(-id) |>
  ggplot(aes(name, value, group = id)) +
  geom_line(alpha = .3) +
  geom_smooth(aes(group = 1), method = lm, smooth = FALSE) +
  scale_y_continuous(sec.axis = sec_axis(~ rescale(.x, range_rank, rev(range_appeared)))) +
  scale_x_discrete(expand = c(0, .1))
```


```{r eval=FALSE}
ggplot(languages_filtered1, aes(y = rank_bin, x = appeared, fill = rank %in% 1:10)) +
  geom_hline(aes(yintercept = rank_bin)) +
  stat_dotsinterval(side = "top", scale = 0.7, slab_linewidth = NA) +
  scale_y_discrete(labels = rev(c("Top 100", seq(200, 1000, 100)))) +
  scale_x_continuous(limits = c(1940, 2030)) +
  scale_fill_manual(values = c("grey80", "red")) +
  guides(fill = "none")
```
